### ISSUE TITLE
Link to binaries is no longer valid

### ISSUE THREAD

**Issue by Asuranceturix** [geek1011/bootnext#1]
The site that held the binaries apparently deletes them after 6 months.

**Comment by pgaskin** [comment]
Ok, thanks for reminding me. I'll trigger a rebuild.

**Comment by pgaskin** [comment]
https://ci.appveyor.com/project/geek1011/bootnext/builds/26314381

**Comment by Asuranceturix** [comment]
So fast! Thanks a lot!
