### ISSUE TITLE
GetFirmwareType missing in kernel32.dll

### ISSUE THREAD

**Issue by josephernest** [geek1011/bootnext#3]
Congrats for this nice project that looks nice!

I have this error message on Windows 7 x64:

![image](https://user-images.githubusercontent.com/6168083/85370417-f9a9cf80-b52e-11ea-8d0b-9c89e827e20e.png)

Is it possible to build a version for Windows 7 @geek1011?

**Comment by pgaskin** [comment]
I'll look into that. The cause of this issue is that `GetFirmwareType` isn't supported until Windows 8, but hopefully it's just that one (which I can skip if necessary).

**Comment by pgaskin** [comment]
This [change](https://ci.appveyor.com/project/geek1011/bootnext/builds/33701054/artifacts) should fix the issue.

**Comment by josephernest** [comment]
Thanks @geek1011 I'm going to try with this!
